version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
       - .:/usr/src/app

  web:
    build: .
    container_name: web-1
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mvtdb
    ports:
      - "80:80"
      - "443:443"

volumes:
  mongo_data: